server:
  port: 8910
spring:
 datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: koud
    password: 12345
    platform: POSTGRESQL
    driverClassName: org.postgresql.Driver
logging:
  path: \home\poetryapp\logs\authLogs
signing.key: "12345"
