spring:
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.PostgreSQL94Dialect
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.lob.non_contextual_creation: false
      hibernate.id.new_generator_mappings: true
      hibernate.generate_statistics: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # url: jdbc:postgresql://localhost:5432/users
    # username: koud
    # password: 12345
    url: jdbc:postgresql://poetryapp-postgres.c42mexo56bge.eu-central-1.rds.amazonaws.com:5432/poetryapp
    username: poetryapp_master
    password: bYox47o;Hgb-PX*S
    platform: POSTGRESQL
  sleuth:
     sampler:
      probability: 1.0
     web:
        skipPattern: (^cleanup.*|.+favicon.*)
server:
  port: 8400
management:
 endpoints:
  web:
   exposure:
    include: '*'
logging:
  path: poemLogs
signing.key: "12345"
smsIn.url: http://mbc.mobc.com:8030/VotingSmsIn/SmsIN.asmx
smsIn.UserName: webserIn
smsIn.UserPass: 2012@SMS_mbc
voting.cost: 20
