spring:
  jpa:
    hibernate:
      ddl-auto: none
      database-platform: org.hibernate.dialect.PostgreSQL94Dialect
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      naming.physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      connection.provider_class: org.hibernate.hikaricp.internal.HikariCPConnectionProvider
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
      hibernate.jdbc.lob.non_contextual_creation: false
      hibernate.id.new_generator_mappings: true
      hibernate.generate_statistics: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/users
    username: koud
    password: 12345
    #url: jdbc:postgresql://poetryapp-postgres.c42mexo56bge.eu-central-1.rds.amazonaws.com:5432/poetryapp
    #username: poetryapp_master
    #password: bYox47o;Hgb-PX*S
    platform: POSTGRESQL
  sleuth:
     sampler:
      probability: 1.0
     web:
        skipPattern: (^cleanup.*|.+favicon.*)
server:
  port: 8700
management:
 endpoints:
  web:
   exposure:
    include: '*'
logging:
  path: \home\poetryapp\logs\userLogs
signing.key: "12345"
public.key: C2AV5hCnG31gwmVfkLuZ
private.key: ZBgMBYVtxHYR3C1H6bL5
api.url: http://staging.tpay.me/api/TPay.svc/json/InitializeDirectPaymentTransaction
api.resendUrl: http://staging.tpay.me/api/TPay.svc/json/ResendVerificationPin
api.confirmationUrl: http://staging.TPAY.me/api/TPAY.svc/Json/ConfirmDirectPaymentTransaction
