firebase.server.key: AAAAzBNVK2o:APA91bEAnNKEFjhIf1Ro2kViXZHb5_ObUNI0sEA54hhtrIldCcqMgcUM982rBfTtTsU5Yvfau78cd3dwbqsq6KGWMIM-XoUeWCD6RPFk8dHUzcA3Qc2D19wJ2XKeMe7MNJuzDIlKxFP7JJMVgMJZTWpa5SLripfwHg
firebase.api.url: https://fcm.googleapis.com/fcm/send
spring:
  sleuth:
     sampler:
      probability: 1.0
     web:
        skipPattern: (^cleanup.*|.+favicon.*)
server:
  port: 8900
management:
 endpoints:
  web:
   exposure:
    include: '*'
logging:
  path: \home\poetryapp\logs\firebaseLogs
signing.key: "12345"
