server:
 port: 8800
zuul:
 prefix: /api
 sensitive-headers: Cookie,Set-Cookie
ribbon:
 eureka:
  enabled: true
spring:
  application:
    name: zuul-proxy
eureka:
 instance:
    prefer-ip-address: true
 client:
  enabled: true
  register-with-eureka: true
  fetch-registry: true
management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: '*'
logging:
  path: \home\poetryapp\logs\zuulLogs
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 60000

